# Generated by Django 4.0.6 on 2022-07-07 10:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.writer')),
            ],
        ),
    ]
